version: '3.7'
services:
  platon:
    image: shinnng/platon-go:latest
    container_name: stress3
    volumes:
    - /data/platon-stress/node3:/data/platon
    network_mode: host
    environment:
      ENABLE_DEBUG: 'true'
      ENABLE_PPROF: 'true'
      ENABLE_WS: 'true'
      WSAPI: platon,debug,txpool,metrics,admin,net
      ENABLE_RPC: 'true'
      RPCAPI: platon,debug,txpool,metrics,admin,net
      VERBOSITY: 1
      INIT: 'true'
      NEW_ACCOUNT: 'true'
      ENABLE_DISCOVER: 'true'
      P2PPORT: '16789'
      WSPORT: '7789'
      RPCPORT: '6789'
      PPROFPORT: '8789'
      DISABLEDBGC: 'false'
      DBGCINTERVAL: 1000
      DBGCTIMEOUT: 5m
      DBGCMPT: 'true'
      MAXPEERS: 50
      HOST: 0.0.0.0
      CACHE_TRIEDB: 512
      BOOTNODES: enode://64a055248bf1ecf9cd21e11c2c537a25bae9b1dad764937c0d06914cd720d7ec633ee62c8af7c73e3f9da687a7f90ba68019bbad0b8265d6d21a0dc7e1143eff@192.168.120.124:16790
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.120.123:9789
        tag: platon
        fluentd-async-connect: 'true'
    depends_on:
    - fluent
  fluent:
    network_mode: host
    image: fluentd
    container_name: stress3-fluent
    volumes:
    - /data/platon-stress/node3/fluent.conf:/fluentd/etc/fluent.conf
    - /data/platon-stress/node3/log:/data/log/
