version: '3.7'
services:
  platon:
    image: shinnng/platon-go:latest
    container_name: stress7
    volumes:
    - /data/platon-stress/node7:/data/platon
    network_mode: host
    environment:
      ENABLE_DEBUG: 'true'
      ENABLE_PPROF: 'true'
      ENABLE_WS: 'true'
      WSAPI: platon,debug,txpool,metrics,admin,net
      ENABLE_RPC: 'true'
      RPCAPI: platon,debug,txpool,metrics,admin,net
      VERBOSITY: 1
      INIT: 'true'
      NEW_ACCOUNT: 'true'
      ENABLE_DISCOVER: 'true'
      P2PPORT: '16790'
      WSPORT: '7790'
      RPCPORT: '6790'
      PPROFPORT: '8790'
      DISABLEDBGC: 'false'
      DBGCINTERVAL: 1000
      DBGCTIMEOUT: 5m
      DBGCMPT: 'true'
      MAXPEERS: 50
      HOST: 0.0.0.0
      CACHE_TRIEDB: 512
      BOOTNODES: enode://64a055248bf1ecf9cd21e11c2c537a25bae9b1dad764937c0d06914cd720d7ec633ee62c8af7c73e3f9da687a7f90ba68019bbad0b8265d6d21a0dc7e1143eff@192.168.120.124:16790
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.120.122:9790
        tag: platon
        fluentd-async-connect: 'true'
    depends_on:
    - fluent
    - staking
  fluent:
    network_mode: host
    image: fluentd
    container_name: stress7-fluent
    volumes:
    - /data/platon-stress/node7/fluent.conf:/fluentd/etc/fluent.conf
    - /data/platon-stress/node7/log:/data/log/
  staking:
    network_mode: host
    image: shinnng/platon-go:bech32
    container_name: stress7-staking
    environment:
      USE_CMD: batch_staking
      URL: ws://127.0.0.1:7790
      NODENAME: stress7
      BLSKEY: 2551173fead37b185c6fde2860bbbcb69308e3f92f27f6eb63a1251f6b1ef524
      NODEKEY: ce5b1db91c1b14f056bf08220a555bc45f8e6e7f4d294f640aca95507432391b
      PRIVATE_KEY: dcfb7d0babf20d4ecec0ddd140aa138a81224c66f38867a18c7b8b740314b864
      PROGRAM_VERSION: 3329
      CHAINID: 101
