version: '3.7'
services:
  platon:
    image: shinnng/platon-go:latest
    container_name: stress8
    volumes:
    - /data/platon-stress/node8:/data/platon
    network_mode: host
    environment:
      ENABLE_DEBUG: 'true'
      ENABLE_PPROF: 'true'
      ENABLE_WS: 'true'
      WSAPI: platon,debug,txpool,metrics,admin,net
      ENABLE_RPC: 'true'
      RPCAPI: platon,debug,txpool,metrics,admin,net
      VERBOSITY: 1
      INIT: 'true'
      NEW_ACCOUNT: 'true'
      ENABLE_DISCOVER: 'true'
      P2PPORT: '16790'
      WSPORT: '7790'
      RPCPORT: '6790'
      PPROFPORT: '8790'
      DISABLEDBGC: 'false'
      DBGCINTERVAL: 1000
      DBGCTIMEOUT: 5m
      DBGCMPT: 'true'
      MAXPEERS: 50
      HOST: 0.0.0.0
      CACHE_TRIEDB: 512
      BOOTNODES: enode://64a055248bf1ecf9cd21e11c2c537a25bae9b1dad764937c0d06914cd720d7ec633ee62c8af7c73e3f9da687a7f90ba68019bbad0b8265d6d21a0dc7e1143eff@192.168.120.124:16790
    logging:
      driver: fluentd
      options:
        fluentd-address: 192.168.120.123:9790
        tag: platon
        fluentd-async-connect: 'true'
    depends_on:
    - fluent
    - staking
  fluent:
    network_mode: host
    image: fluentd
    container_name: stress8-fluent
    volumes:
    - /data/platon-stress/node8/fluent.conf:/fluentd/etc/fluent.conf
    - /data/platon-stress/node8/log:/data/log/
  staking:
    network_mode: host
    image: shinnng/platon-go:bech32
    container_name: stress8-staking
    environment:
      USE_CMD: batch_staking
      URL: ws://127.0.0.1:7790
      NODENAME: stress8
      BLSKEY: c9c3c1a76a879f1330c2d9ad5ee631e995038ca91df02d27fe3616323a2d3843
      NODEKEY: 056753ca473fb1758765713e1be2f6d0132cd03ff6936469ce4286f28a8fddf0
      PRIVATE_KEY: 62c0b45ef7ba4965adb1fb2a2f0e065da6bd7857ce117df552004d0002d3f948
      PROGRAM_VERSION: 3329
      CHAINID: 101
