version: '3.7'
services:
  es01:
    image: docker.io/elasticsearch:7.5.0
    container_name: es01
    environment:
      - node.name=es01
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata01:/usr/share/elasticsearch/data
      - esconfig01:/usr/share/elasticsearch/config
    ports:
      - 9200:9200
    networks:
      - esnet
  
  kibana:
    image: docker.io/kibana:7.5.0
    container_name: kibana
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://localhost:9200
      ELASTICSEARCH_URL: http://localhost:9200
    ports:
      - 5601:5601
    volumes:
      - kibana:/usr/share/kibana/config

volumes:
  esdata01:
    driver: local
  esconfig01:
    driver: local
  kibana:
    driver: local

networks:
  esnet: